Add biocViews to description
Adding biocViews: to the description allows the DESeq2 dependency to be installed automatically from Bioconductor.  Otherwise this happens:
```r
> devtools::install_github("immunogenomics/presto")
Downloading GitHub repo immunogenomics/presto@master
Skipping 1 packages not available: DESeq2
Installing 2 packages: DESeq2, RcppArmadillo
Error: Failed to install 'presto' from GitHub:
  (converted from warning) package ‘DESeq2’ is not available (for R version 3.6.3)
```